export default {
  ADVERTISEMENTS: 'ADVERTISEMENTS',
  BLEETER: 'BLEETER',
  SERVICES: 'SERVICES',
  TWITTER: 'TWITTER',
  MATCH: 'MATCH',
  MESSAGES: 'MESSAGES',
  NOTES: 'NOTES',
  MARKETPLACE: 'MARKETPLACE',
  CONTACTS: 'CONTACTS',
  CAMERA: 'CAMERA',
  PHONE: 'PHONE',
};
